"""Create initial tables

<<<<<<<< HEAD:aa19-python-group-project/migrations/versions/04ca22b7f06e_initial_migration.py
Revision ID: 04ca22b7f06e
Revises: 
Create Date: 2025-07-23 10:15:09.805241
========
Revision ID: dc5261b12dd5
Revises: 
Create Date: 2025-07-23 19:31:40.374231
>>>>>>>> dev:aa19-python-group-project/migrations/versions/dc5261b12dd5_create_initial_tables.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:aa19-python-group-project/migrations/versions/04ca22b7f06e_initial_migration.py
revision = '04ca22b7f06e'
========
revision = 'dc5261b12dd5'
>>>>>>>> dev:aa19-python-group-project/migrations/versions/dc5261b12dd5_create_initial_tables.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('goal', sa.Integer(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('genre', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('goal', sa.Integer(), nullable=False),
    sa.Column('current_amount', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
<<<<<<<< HEAD:aa19-python-group-project/migrations/versions/04ca22b7f06e_initial_migration.py
========
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
>>>>>>>> dev:aa19-python-group-project/migrations/versions/dc5261b12dd5_create_initial_tables.py
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
<<<<<<<< HEAD:aa19-python-group-project/migrations/versions/04ca22b7f06e_initial_migration.py
========
    op.drop_table('project_categories')
    op.drop_table('donations')
    op.drop_table('comments')
>>>>>>>> dev:aa19-python-group-project/migrations/versions/dc5261b12dd5_create_initial_tables.py
    op.drop_table('projects')
    op.drop_table('campaigns')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
